# Generated by Django 4.2.2 on 2023-06-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_seguimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='historial',
        ),
    ]
