# Generated by Django 4.2.2 on 2023-06-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_itemcarrito_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='estado',
            field=models.CharField(default='pendiente', max_length=100),
        ),
    ]
