# Generated by Django 4.2.2 on 2023-06-21 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_itemcarrito_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='estado',
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='historial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.historial'),
        ),
    ]
