# Generated by Django 4.2.2 on 2023-06-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_itemcarrito_estado_itemcarrito_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='historial',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
